FROM docker.io/cytopia/phpcs:3-php7.4

RUN apk add git coreutils bash

RUN git clone -b 2.3.0 https://github.com/WordPress/WordPress-Coding-Standards.git /wpcs

RUN phpcs --config-set installed_paths /wpcs

WORKDIR /root/workspace

# keep container running for development work
# (e.g. vscode remote development plugin)
# don't do this other than for development purposes
ENTRYPOINT ["tail", "-f", "/dev/null"]