FROM docker.io/library/wordpress:6

RUN sed -i "s/80/8080/" /etc/apache2/sites-enabled/000-default.conf && \
    sed -i "s/Listen 80/Listen 8080/" /etc/apache2/ports.conf

RUN apt-get update && apt-get install less && rm -rf /var/lib/apt/lists/*

COPY resources/wordpress-install.sh /bin/wordpress-install
RUN chmod a+x /bin/wordpress-install

USER root