FROM docker.io/phpdoc/phpdoc:3

# keep container running for development work
# (e.g. vscode remote development plugin)
# don't do this other than for development purposes
ENTRYPOINT ["tail", "-f", "/dev/null"]