version: '3.1'

services:

  database:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql:Z

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${DATA_DIR}/html:/var/www/html:Z
      - ${WORKSPACE_DIR}/code/packages/vb-crossref:/var/www/html/wp-content/plugins/vb-crossref:Z
      - ${WORKSPACE_DIR}/code/packages/vb-gnd-taxonomy:/var/www/html/wp-content/plugins/vb-gnd-taxonomy:Z
      - ${WORKSPACE_DIR}/code/packages/vb-marc21xml-export:/var/www/html/wp-content/plugins/vb-marc21xml-export:Z
      - ${WORKSPACE_DIR}/code/packages/vb-oai-pmh:/var/www/html/wp-content/plugins/vb-oai-pmh:Z
    depends_on:
      - database

  phpmyadmin:
    image: docker.io/library/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database