version: '3.1'

services:

  database:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql:Z

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SAVEQUERIES', true );
    volumes:
      - ${DATA_DIR}/wordpress:/var/www/html:Z
      - ${WORKSPACE_DIR}/code/packages/vb-crossref-doi:/var/www/html/wp-content/plugins/vb-crossref-doi:Z
      - ${WORKSPACE_DIR}/code/packages/vb-doaj-submit:/var/www/html/wp-content/plugins/vb-doaj-submit:Z
      - ${WORKSPACE_DIR}/code/packages/vb-gnd-taxonomy:/var/www/html/wp-content/plugins/vb-gnd-taxonomy:Z
      - ${WORKSPACE_DIR}/code/packages/vb-metadata-export:/var/www/html/wp-content/plugins/vb-metadata-export:Z
    depends_on:
      - database

  phpmyadmin:
    image: docker.io/library/phpmyadmin
    restart: always
    ports:
      - "0.0.0.0:8081:80/tcp"
    environment:
      - PMA_HOST=database
    depends_on:
      - database

  oaipmh-validator:
    build:
      context: .
      dockerfile: Dockerfile.oaipmh-validator
    network_mode: "host"
    depends_on:
      - wordpress