deploymentApiVersion: apps/v1
service:
    internalPort: 80
ingress:
    annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: "basic"
        nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
